using System;

namespace Dafist.Engine.Resilience.SchemaErrors
{
    /// <summary>
    /// recognize schema related internal errors
    /// internal error: exception generated by the engine; not from an external system
    /// </summary>
    public static class InternalSchemaErrorRecognizer
    {
        public static bool IsInternalSchemaError(this Exception x)
        {
            return x is SchemaErrorException ||
                   x is FieldNotFoundException;
        }
    }
}
